"""Added comment query API request

Revision ID: 425f77048afa
Revises: 6afacda4ef15
Create Date: 2023-10-29 06:22:24.172438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425f77048afa'
down_revision: Union[str, None] = '6afacda4ef15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_query',
    sa.Column('query_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('user_character', sa.Text(), nullable=True),
    sa.Column('user_goals', sa.Text(), nullable=True),
    sa.Column('user_style_example', sa.Text(), nullable=True),
    sa.Column('user_style_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('query_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_query')
    # ### end Alembic commands ###
