"""Add post-time to context query

Revision ID: 5712332097ee
Revises: def810f2a780
Create Date: 2023-10-29 07:38:20.947461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5712332097ee'
down_revision: Union[str, None] = 'def810f2a780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('context_summary_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('context_summary_query', schema=None) as batch_op:
        batch_op.drop_column('post_time')

    # ### end Alembic commands ###
