"""Added task-comment-query table

Revision ID: 739bfb18547c
Revises: 8893f1de3f81
Create Date: 2023-10-29 06:41:29.644932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739bfb18547c'
down_revision: Union[str, None] = '8893f1de3f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('context_summary_query',
    sa.Column('query_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('user_character', sa.Text(), nullable=True),
    sa.Column('user_goals', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_table('api_comment_task',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment_query.query_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['api_task.task_id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'task_id', name='pk_cid_tid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_comment_task')
    op.drop_table('context_summary_query')
    op.drop_table('api_task')
    # ### end Alembic commands ###
