"""Made task_id unique

Revision ID: def810f2a780
Revises: 739bfb18547c
Create Date: 2023-10-29 07:05:49.080306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def810f2a780'
down_revision: Union[str, None] = '739bfb18547c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_context_task',
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['context_summary_query.query_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['api_task.task_id'], ),
    sa.PrimaryKeyConstraint('context_id', 'task_id', name='pk_cid_tid'),
    sa.UniqueConstraint('task_id', name='unique_tid')
    )
    with op.batch_alter_table('api_comment_task', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_tid', ['task_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_comment_task', schema=None) as batch_op:
        batch_op.drop_constraint('unique_tid', type_='unique')

    op.drop_table('api_context_task')
    # ### end Alembic commands ###
