# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_message.ipynb.

# %% auto 0
__all__ = ['Message']

# %% ../nbs/01_message.ipynb 3
from datetime import datetime
from dataclasses import dataclass

# %% ../nbs/01_message.ipynb 4
@dataclass
class Message:
    author: str
    time: datetime
    content: str

    def __str__(self) -> str:
        time = self.time.strftime("%d %b %Y %H:%M")
        return f"@{self.author.strip()} ({time}):\n{self.content.strip()}"
